export const tagTypes = {
  login: 'login',
  category: 'category',
  language: 'language',
  product: 'product',
  sizes: 'sizes',
  color: 'color',
  brand: 'brand',
  newArrivals: 'newArrivals',
  hotSale: 'hotSale',
  menCollection: 'menCollection',
  womenCollection: 'womenCollection',
  accessoriesCollection: 'accessoriesCollection',
  singleProduct: 'singleProduct',
  categoryProduct: 'categoryProduct',
  customerRegister: 'customerRegister',
  orderDetails: 'orderDetails',
  customerOrderDetails: 'customerOrderDetails',
}

export const tagTypesList = [
  tagTypes.login,
  tagTypes.category,
  tagTypes.language,
  tagTypes.product,
  tagTypes.sizes,
  tagTypes.color,
  tagTypes.brand,
  tagTypes.newArrivals,
  tagTypes.hotSale,
  tagTypes.menCollection,
  tagTypes.womenCollection,
  tagTypes.accessoriesCollection,
  tagTypes.singleProduct,
  tagTypes.categoryProduct,
  tagTypes.customerRegister,
  tagTypes.orderDetails,
  tagTypes.customerOrderDetails,
]
