export const tagTypes = {
  login: 'login',
  category: 'category',
  language: 'language',
  product: 'product',
  sizes: 'attributes',
  color: 'color',
  brand: 'brand',
  newArrivals: 'newArrivals',
  hotSale: 'hotSale',
  menCollection: 'menCollection',
  womenCollection: 'womenCollection',
  accessoriesCollection: 'accessoriesCollection',
  singleProduct: 'singleProduct',
}

export const tagTypesList = [
  tagTypes.login,
  tagTypes.category,
  tagTypes.language,
  tagTypes.product,
  tagTypes.sizes,
  tagTypes.color,
  tagTypes.brand,
  tagTypes.newArrivals,
  tagTypes.hotSale,
  tagTypes.menCollection,
  tagTypes.womenCollection,
  tagTypes.accessoriesCollection,
  tagTypes.singleProduct,
]
